FROM node:gallium-alpine
WORKDIR /myapp
COPY / ./
COPY package*.json ./
RUN npm install @angular/cli@latest -g
RUN npm install http-server -g
RUN npm install
RUN ng build
COPY . .
EXPOSE 4200
CMD ["http-server","-p","4200","dist/myapp"]

